FROM python:3.11-slim-buster
WORKDIR /app
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
    cmake \
    build-essential \
    libglib2.0-0 \
    libsm6 \
    libxext6 \
    libxrender1 && \
    rm -rf /var/lib/apt/lists/*
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY app.py .
COPY shape_predictor_68_face_landmarks.dat .
EXPOSE 7860
CMD ["python", "app.py"]
